# Generated by Django 3.0.7 on 2021-03-02 14:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('genre', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('imdb_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dire99popularity', models.CharField(blank=True, max_length=6, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
