# Generated by Django 3.0.7 on 2021-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='imdb_score',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
