# Generated by Django 3.0.7 on 2021-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210302_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
